In [68]:
import pandas as pd
import json
import numpy as np
from IPython.display import display

# Different samples

## All users

In [ ]:
user_cards = pd.read_csv("./player_cards.csv")
card_cols = user_cards.columns[1:]
user_cards['num_cards'] = (user_cards[card_cols] > 0).sum(axis=1)
user_cards

,tag,26000000,26000001,26000002,26000003,26000004,26000005,26000006,26000007,26000008,...,28000014,28000015,28000016,28000017,28000018,28000023,28000024,28000025,28000026,num_cards
0,#VL0QCY9R8,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,121
1,#L0092LLGP,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,121
2,#LU2QQJU0Y,1,1,1,1,1,2,1,1,1,...,1,1,1,1,1,1,1,1,1,121
3,#999QV8RJU,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,121
4,#2G22QVP89,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,#UJRGJGYJG,1,2,1,1,1,1,1,1,1,...,1,1,1,1,1,0,1,0,1,98
69996,#20YQV9Y9GQ,2,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,0,1,111
69997,#CJVL82CQC,1,1,1,1,1,1,1,2,1,...,1,1,1,1,1,0,0,0,1,101
69998,#CJQYRRY0G,1,1,1,1,1,1,1,2,1,...,1,1,1,1,1,0,1,0,1,92
69999,#20QG2P222P,1,1,1,1,1,1,1,2,1,...,1,1,0,1,0,0,0,0,1,86

In [ ]:
user_stats = pd.read_csv("./player_stats.csv")
user_stats['win_rate'] = user_stats['wins'] / (user_stats['wins'] + user_stats['losses'])
user_stats = user_stats.merge(user_cards[['tag', 'num_cards']], on='tag', how='left')
user_stats

,tag,name,expLevel,trophies,bestTrophies,wins,losses,battleCount,threeCrownWins,arena,clan,favCard,starPoints,expPoints,totalExpPoints,win_rate,num_cards
0,#VL0QCY9R8,grokiki,61,10000,10000,3528,1373,4901,1719,Legendary Arena,! ares ¡,Bandit,755009.0,28938,2082708,0.719853,121
1,#L0092LLGP,groskyja,70,10000,10000,10171,6185,16356,7829,Legendary Arena,! ares ¡,Mega Knight,5000000.0,0,7163219,0.621851,121
2,#LU2QQJU0Y,max ツ,62,10000,10000,5751,4678,10429,2594,Legendary Arena,! ares ¡,Electro Dragon,476756.0,205935,2559705,0.551443,121
3,#999QV8RJU,NLE_Freezer56,56,10000,10000,2959,2970,5929,1593,Legendary Arena,! ares ¡,Goblin Giant,264675.0,94330,1023100,0.499072,121
4,#2G22QVP89,Samshiro,65,10000,10000,13762,14743,28505,6779,Legendary Arena,! ares ¡,Royal Recruits,936182.0,22091,3425861,0.482792,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,#UJRGJGYJG,mighty mill,30,5151,5152,573,455,1028,332,Miner's Mine,OUTSKIRT,Mega Knight,5279.0,2984,41754,0.557393,98
69996,#20YQV9Y9GQ,snakejem12,34,5140,5345,507,364,871,320,Miner's Mine,OUTSKIRT,The Log,34567.0,3497,77267,0.582090,111
69997,#CJVL82CQC,Pexgan,32,4993,4993,366,211,577,266,Serenity Peak,OUTSKIRT,Goblin Gang,13341.0,1030,54800,0.634315,101
69998,#CJQYRRY0G,Victor,31,4980,4980,409,286,695,234,Serenity Peak,OUTSKIRT,Witch,575.0,1355,47125,0.588489,92
69999,#20QG2P222P,xbx3trr,28,4792,4792,431,325,756,219,Serenity Peak,OUTSKIRT,Mini P.E.K.K.A,6032.0,4687,32057,0.570106,86

## Baseline users

In [ ]:
baseline_train = pd.read_csv("./train.csv")
baseline_test = pd.read_csv("./test.csv")
baseline_dataset = pd.concat([baseline_train, baseline_test], ignore_index=True)

In [57]:
baseline_users = baseline_dataset["userID"].unique()

In [58]:
baseline_users_stats = user_stats[user_stats["tag"].isin(baseline_users)]
baseline_users_stats

,tag,name,expLevel,trophies,bestTrophies,wins,losses,battleCount,threeCrownWins,arena,clan,favCard,starPoints,expPoints,totalExpPoints,win_rate,num_cards
32,#JUP9RVC2Q,-₹Grãfĩtĩ₹-,53,10000,10000,1381,761,2142,537,Legendary Arena,! ares ¡,Dart Goblin,88288.0,51858,605628,0.644725,121
35,#90R0GR29,Matilin,54,10000,10000,3058,2407,5465,2604,Legendary Arena,! ares ¡,Mega Knight,122874.0,100419,754189,0.559561,121
39,#UJGLJY9L9,pied carré,45,10000,10000,1179,832,2011,490,Legendary Arena,! ares ¡,Witch,51134.0,20634,299404,0.586275,121
52,#28YLCLGGV,berthymus,70,10000,10000,23049,17399,40448,8950,Legendary Arena,!EMPIRE FR!,X-Bow,4578572.0,0,5681467,0.569843,121
54,#9CQU09LRU,Entends ma RAGE,61,10000,10000,7089,7563,14652,3878,Legendary Arena,!EMPIRE FR!,Mega Knight,958705.0,224180,2277950,0.483825,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69958,#QRCQ0JRUJ,DARK_sachou,46,9177,9211,1156,1095,2251,593,Valkalla,OUTSKIRT,Tesla,16278.0,11617,315387,0.513550,121
69959,#VURCYYJVG,finny,43,8767,8769,612,318,930,314,PANCAKES!,OUTSKIRT,Clone,18850.0,1876,230646,0.658065,119
69975,#VVPGYU0VV,SDprint,34,6643,6672,571,384,955,379,Silent Sanctuary,OUTSKIRT,P.E.K.K.A,7852.0,2382,76152,0.597906,114
69989,#20G89GPUGC,Logan,30,5660,5833,481,316,797,224,Executioner's Kitchen,OUTSKIRT,Witch,7024.0,5404,44174,0.603513,103
69990,#UGU0RQ2V0,obliviousJJ,35,5648,5796,626,502,1128,412,Executioner's Kitchen,OUTSKIRT,Skeleton Barrel,13016.0,5221,91491,0.554965,114

## LLM users

In [59]:
unique_users = set()
path = "../results/generations_20251128_082528.jsonl" 

with open(path, 'r', encoding='utf-8') as f:
    for line in f:
        try:
            data = json.loads(line)
            if 'user_id' in data:
                unique_users.add("#" + data['user_id'])
                
        except json.JSONDecodeError:
            continue

print(f"Se encontraron {len(unique_users)} usuarios únicos.")

Se encontraron 300 usuarios únicos.

In [60]:
llm_users_stats = user_stats[user_stats["tag"].isin(unique_users)]
llm_users_stats

,tag,name,expLevel,trophies,bestTrophies,wins,losses,battleCount,threeCrownWins,arena,clan,favCard,starPoints,expPoints,totalExpPoints,win_rate,num_cards
0,#VL0QCY9R8,grokiki,61,10000,10000,3528,1373,4901,1719,Legendary Arena,! ares ¡,Bandit,755009.0,28938,2082708,0.719853,121
1,#L0092LLGP,groskyja,70,10000,10000,10171,6185,16356,7829,Legendary Arena,! ares ¡,Mega Knight,5000000.0,0,7163219,0.621851,121
2,#LU2QQJU0Y,max ツ,62,10000,10000,5751,4678,10429,2594,Legendary Arena,! ares ¡,Electro Dragon,476756.0,205935,2559705,0.551443,121
3,#999QV8RJU,NLE_Freezer56,56,10000,10000,2959,2970,5929,1593,Legendary Arena,! ares ¡,Goblin Giant,264675.0,94330,1023100,0.499072,121
4,#2G22QVP89,Samshiro,65,10000,10000,13762,14743,28505,6779,Legendary Arena,! ares ¡,Royal Recruits,936182.0,22091,3425861,0.482792,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,#GL9820ULC,Aidosk29,56,9211,9330,993,977,1970,844,Valkalla,#Australia 2,Mega Knight,1851.0,76680,1005450,0.504061,121
296,#2CVG00U2J,DABID DANY,51,9148,9148,1519,1007,2526,891,Valkalla,#Australia 2,Mega Knight,26917.0,17076,445846,0.601346,120
297,#PLU0PR0GU,脏啊说我,43,9131,9217,1190,1377,2567,820,Valkalla,#Australia 2,Mega Knight,14843.0,17160,245930,0.463576,120
298,#U0VV0JLP,BadSeed,50,9060,9117,8102,8172,16274,4205,Valkalla,#Australia 2,Royal Giant,348173.0,6725,410495,0.497849,120
299,#2PLG092,Lachlan,49,9053,9053,2430,2069,4499,619,Valkalla,#Australia 2,Miner,25148.0,16710,395480,0.540120,119

# Comparison

In [61]:
def get_column_statistics(df, column):
    mean = df[column].mean()
    median = df[column].median()
    std = df[column].std()

    print(f"[{column}] Media: {mean}, Mediana: {median}, Desviación: {std}")

    return mean, median, std

In [65]:
dataframes = {
    "all": user_stats,
    "baseline": baseline_users_stats,
    "llm": llm_users_stats
}

column_names = ['win_rate', 'expLevel', 'num_cards']

summary = {}

for df_name, df in dataframes.items():
    summary[df_name] = {}
    for column in column_names:
        media, median, std = get_column_statistics(df, column)
        summary[df_name][column] = {
            "media": media,
            "median": median,
            "std": std
        }

[win_rate] Media: 0.5735148051844046, Mediana: 0.5559000556427645, Desviación: 0.0890594852851397
[expLevel] Media: 39.960457142857145, Mediana: 39.0, Desviación: 13.112006749591018
[num_cards] Media: 106.19012857142857, Mediana: 118.0, Desviación: 25.859540183366803
[win_rate] Media: 0.5732058849650131, Mediana: 0.5560890523187135, Desviación: 0.08827105864256451
[expLevel] Media: 39.934583333333336, Mediana: 39.0, Desviación: 13.18091228622335
[num_cards] Media: 106.00691666666667, Mediana: 118.0, Desviación: 25.97894874010864
[win_rate] Media: 0.5431418130101137, Mediana: 0.5366748164674149, Desviación: 0.05672187308115544
[expLevel] Media: 54.89, Mediana: 55.0, Desviación: 8.087599409840154
[num_cards] Media: 120.21, Mediana: 121.0, Desviación: 2.6399110656957006

In [66]:
data = []
for group, vars_dict in summary.items():
    for variable, stats in vars_dict.items():
        for stat_name, value in stats.items():
            data.append({
                'Dataset': group,
                'Game Stat': variable,
                'Metric': stat_name,
                'Value': value
            })

df = pd.DataFrame(data)

tabla_final = df.pivot_table(index='Dataset', 
                             columns=['Game Stat', 'Metric'], 
                             values='Value')

tabla_final = tabla_final.reindex(['all', 'baseline', 'llm'])

In [69]:
format = {
    'win_rate': '{:.1%}',
    'expLevel': '{:.1f}',
    'num_cards': '{:.1f}'
}

for column in column_names:
    sub_tabla = tabla_final[column]
    
    print(f"Estadísticas para: {column}")
    
    if column in format:
        styler = sub_tabla.style.format(format[column])
        display(styler)
    else:
        display(sub_tabla)
        
    print("\n")

Estadísticas para: win_rate

Estadísticas para: expLevel

Estadísticas para: num_cards